---
# Redis role tasks

- name: Install Redis server
  apt:
    name: redis-server
    state: present

- name: Enable and start Redis service
  systemd:
    name: redis-server
    state: started
    enabled: yes

- name: Configure Redis
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Redis

- name: Install Redis PHP extension
  apt:
    name: "php{{ php_version }}-redis"
    state: present
  notify: Restart PHP-FPM